import { StyleSheet } from "@react-pdf/renderer";

export const resumeColors = {
	navy: "#062650",
	deepNavy: "#041d3d",
	blue: "#0754b7",
	cyan: "#00bdf2",
	ink: "#123a72",
	muted: "#284d7d",
	white: "#ffffff",
	line: "#168cff",
} as const;

export const resumeStyles = StyleSheet.create({
	page: {
		position: "relative",
		flexDirection: "row",
		width: "100%",
		height: "100%",
		backgroundColor: resumeColors.white,
		fontFamily: "Helvetica",
		color: resumeColors.ink,
	},
	sidebar: {
		width: "34%",
		paddingTop: 25,
		paddingRight: 16,
		paddingBottom: 18,
		paddingLeft: 18,
		backgroundColor: resumeColors.navy,
		color: resumeColors.white,
	},
	main: {
		width: "66%",
		paddingTop: 13,
		paddingRight: 18,
		paddingBottom: 8,
		paddingLeft: 16,
		backgroundColor: resumeColors.white,
	},
	name: {
		fontSize: 19,
		fontWeight: 700,
		lineHeight: 1,
		color: resumeColors.white,
	},
	role: {
		marginTop: 7,
		fontSize: 10.5,
		fontWeight: 700,
		color: resumeColors.cyan,
	},
	sidebarSection: {
		marginTop: 13,
	},
	sidebarHeading: {
		paddingBottom: 3,
		borderBottomWidth: 0.8,
		borderBottomColor: resumeColors.cyan,
		fontSize: 9.4,
		fontWeight: 700,
		color: resumeColors.cyan,
		textTransform: "uppercase",
	},
	contactRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		marginTop: 5,
	},
	contactMark: {
		width: 13,
		height: 9,
		marginRight: 1,
	},
	contactText: {
		flex: 1,
		fontSize: 6.9,
		lineHeight: 1.18,
		color: resumeColors.white,
	},
	skillGroup: {
		marginTop: 5,
	},
	skillGroupTitle: {
		fontSize: 7.4,
		fontWeight: 700,
		color: resumeColors.cyan,
	},
	skill: {
		marginTop: 1.2,
		paddingLeft: 6,
		fontSize: 6.75,
		lineHeight: 1.08,
		color: resumeColors.white,
	},
	language: {
		marginTop: 3,
		fontSize: 7,
		color: resumeColors.white,
	},
	mainSection: {
		marginBottom: 4,
	},
	sectionTitleRow: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 3,
		paddingBottom: 2,
		borderBottomWidth: 0.8,
		borderBottomColor: resumeColors.line,
	},
	sectionIcon: {
		width: 19,
		height: 13,
		marginRight: 2,
	},
	sectionTitle: {
		fontSize: 11,
		fontWeight: 700,
		color: resumeColors.blue,
		textTransform: "uppercase",
	},
	summary: {
		fontSize: 7.25,
		lineHeight: 1.2,
		color: resumeColors.ink,
	},
	job: {
		position: "relative",
		paddingLeft: 12,
		marginBottom: 4,
	},
	jobDot: {
		position: "absolute",
		top: 2,
		left: 0,
		width: 6,
		height: 6,
		borderRadius: 3,
		backgroundColor: resumeColors.line,
	},
	jobHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-start",
	},
	jobTitle: {
		maxWidth: "72%",
		fontSize: 7.6,
		fontWeight: 700,
		color: resumeColors.ink,
	},
	date: {
		fontSize: 6.7,
		color: resumeColors.line,
	},
	company: {
		marginTop: 1,
		fontSize: 6.8,
		fontStyle: "italic",
		color: resumeColors.blue,
	},
	bullet: {
		marginTop: 1.2,
		paddingLeft: 7,
		fontSize: 6.95,
		lineHeight: 1.1,
		color: resumeColors.ink,
	},
	project: {
		position: "relative",
		paddingLeft: 12,
		marginBottom: 2,
	},
	projectDot: {
		position: "absolute",
		top: 2,
		left: 1,
		width: 5,
		height: 5,
		borderRadius: 2.5,
		backgroundColor: resumeColors.line,
	},
	projectHeader: {
		flexDirection: "row",
		alignItems: "baseline",
	},
	projectName: {
		fontSize: 7.4,
		fontWeight: 700,
		color: resumeColors.ink,
	},
	projectTech: {
		marginLeft: 5,
		fontSize: 6.2,
		fontStyle: "italic",
		color: resumeColors.blue,
	},
	projectDescription: {
		marginTop: 1,
		fontSize: 6.65,
		lineHeight: 1.08,
		color: resumeColors.ink,
	},
	certification: {
		position: "relative",
		paddingLeft: 12,
		marginBottom: 3,
	},
	certificationDot: {
		position: "absolute",
		top: 2,
		left: 1,
		width: 5,
		height: 5,
		borderRadius: 2.5,
		backgroundColor: resumeColors.line,
	},
	certificationName: {
		fontSize: 6.9,
		fontWeight: 700,
		color: resumeColors.ink,
	},
	certificationIssuer: {
		marginTop: 1,
		fontSize: 6.2,
		fontStyle: "italic",
		color: resumeColors.blue,
	},
	footer: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginTop: 2,
		paddingTop: 4,
		borderTopWidth: 0.8,
		borderTopColor: resumeColors.line,
		fontSize: 6.5,
		color: resumeColors.blue,
	},
});
